# Generated by Django 5.2.7 on 2025-11-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coverage_percent', models.FloatField(blank=True, null=True)),
                ('total_tests', models.IntegerField(blank=True, null=True)),
                ('failures', models.IntegerField(blank=True, null=True)),
                ('errors', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Test run duration in seconds', null=True)),
                ('report_path', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(default='ok', help_text='ok/failed', max_length=32)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
